#!/usr/bin/env bash

# This is Aleksana's bash theme. Because all bash themes sucks, or 
# simply don't meet my requirements, I made this as my daily driver.

# I'm trying to make the scripts structured and self-explanatory.

source $(dirname $0)/functions.sh

PROMPT_COMMAND=prompting
prompting() {
	last_exitcode=$?
	# set prompt order
	prompts="$(get_hostname) :: $(get_path) $(get_gitstatus) $(get_arrow ${last_exitcode})"
	
	# apply the prompt
	PS1="$(trim_all "${prompts}") "
	export PS1
}
